#!/bin/sh

# 日志重定向
exec >/tmp/setup.log 2>&1

# Set a default root password if not already set
(echo "password"; sleep 1; echo "password") | passwd > /dev/null

# 设置主机ip地址 
uci set network.lan.ipaddr='192.168.10.1'



# 设置 DHCP 租期
uci set dhcp.lan.leasetime="2m"

# # 添加静态 DHCP 租约
# uci add dhcp host
# uci add_list dhcp.@host[-1].mac="6A:CE:3B:D4:CB:8B"
# uci set dhcp.@host[-1].ip="192.168.10.158"

# uci add dhcp host
# uci add_list dhcp.@host[-1].mac="30:9C:23:E1:E3:72"
# uci set dhcp.@host[-1].ip="192.168.10.107"

# uci add dhcp host
# uci add_list dhcp.@host[-1].mac="7C:2B:E1:13:6E:83"
# uci set dhcp.@host[-1].ip="192.168.10.180"



# # 配置 zerotier
# # uci set zerotier.sample_config.enabled="1"
# # uci del zerotier.sample_config.join
# # uci add_list zerotier.sample_config.join="d3ecf5726da3eeac"
# # uci set zerotier.sample_config.nat="1"
# # uci del zerotier.earth.enabled
# # uci del zerotier.earth.allow_managed
# # uci del zerotier.earth.allow_default
# # uci del zerotier.earth.allow_dns
# # uci del zerotier.earth.fw_allow_input
# # uci del zerotier.earth.fw_allow_forward
# # uci del zerotier.earth.fw_allow_masq
# # uci set zerotier.earth.allow_global='1'
# # uci del zerotier.global.enabled
# # uci set zerotier.earth.id='d3ecf5726da3eeac'
# # sleep 1
# # uci commit zerotier

# # 配置 vlmcsd 服务
# uci set vlmcsd.config.enabled="1"
# uci set vlmcsd.config.auto_activate="1"
# uci set vlmcsd.config.internet_access="1"


# 提交 system（可选）
uci commit system

echo "All done!"
exit 0