name: Test Script

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run script
      run: |
        chmod +x smpackage/immortalwrt-all-2.sh
        ./smpackage/immortalwrt-all-2.sh

    - name: Verify output
      run: |
        echo "Contents of 99-MY-settings:"
        cat package/emortal/default-settings/files/99-MY-settings
